<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vendingMachineUAQ" nsURI="http://www.example.org/vendingMachineUAQ"
    nsPrefix="vendingMachineUAQ">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NamedEntity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VendingMachine" eSuperTypes="/VendingMachineUAQ/model/vendingMachineUAQ.ecore#//NamedEntity /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//HasId">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="ecore:EClass /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//Location"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="ecore:EClass /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//State"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keypad" lowerBound="1"
        eType="ecore:EClass /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//Keypad"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paymentProcessor" lowerBound="1"
        eType="ecore:EClass /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//PaymentProcessor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemProcessor" lowerBound="1"
        eType="ecore:EClass /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//ItemProcessor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inventory" lowerBound="1"
        eType="ecore:EClass /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//Inventory"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="/VendingMachineUAQ/model/vendingMachineUAQ.ecore#//NamedEntity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidCoordinates"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidCoordinates" value="self.lat >= -90 and self.lat &lt;= 90 and self.long >= -180 and self.long &lt;= 180"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lat" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="long" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasId" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Keypad" eSuperTypes="/VendingMachineUAQ/model/vendingMachineUAQ.ecore#//HasOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="ecore:EEnum /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//STATE_OPERATIONS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemProcessor" eSuperTypes="/VendingMachineUAQ/model/vendingMachineUAQ.ecore#//HasOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="ecore:EClass /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentStage" lowerBound="1"
        eType="ecore:EEnum /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//STATES">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.state.stage"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stage" lowerBound="1" eType="ecore:EEnum /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//STATES"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="STATE_OPERATIONS">
    <eLiterals name="SELECT_ITEM_collectCoin"/>
    <eLiterals name="SELECT_ITEM_sendInput" value="1"/>
    <eLiterals name="PROCESSING_ITEM_processItem" value="2"/>
    <eLiterals name="ITEM_DISPATCHED_dispatchChange" value="3"/>
    <eLiterals name="WAIT_FOR_PAYMENT_collectCoin" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PAYMENT_METHODS">
    <eLiterals name="Coin"/>
    <eLiterals name="App" value="1"/>
    <eLiterals name="NFC" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="STATES">
    <eLiterals name="SELECT_ITEM"/>
    <eLiterals name="WAIT_FOR_PAYMENT" value="1"/>
    <eLiterals name="PROCESSING_PAYMENT" value="2"/>
    <eLiterals name="PROCESSING_ITEM" value="3"/>
    <eLiterals name="ITEM_DESPATCHED" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentProcessor" eSuperTypes="/VendingMachineUAQ/model/vendingMachineUAQ.ecore#//HasOperation">
    <eOperations name="isPaymentComplete" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.state.stage = STATES::PROCESSING_PAYMENT and not self.paymentMethod.oclIsUndefined()"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amound" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paymentMethod" lowerBound="1"
        eType="ecore:EEnum /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//PAYMENT_METHODS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="ecore:EClass /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemGroup" eSuperTypes="/VendingMachineUAQ/model/vendingMachineUAQ.ecore#//HasId /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//NamedEntity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PositiveQuantity"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="PositiveQuantity" value="self.quantity > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="ecore:EClass /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//Item"
        containment="true" eOpposite="/VendingMachineUAQ/model/vendingMachineUAQ.ecore#//Item/itemGroup"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="/VendingMachineUAQ/model/vendingMachineUAQ.ecore#//HasId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expiry" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemGroup" lowerBound="1"
        eType="ecore:EClass /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//ItemGroup"
        eOpposite="/VendingMachineUAQ/model/vendingMachineUAQ.ecore#//ItemGroup/items"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inventory" eSuperTypes="/VendingMachineUAQ/model/vendingMachineUAQ.ecore#//HasId">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NonNegativeCapacity"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NonNegativeCapacity" value="self.capacity >= 0"/>
    </eAnnotations>
    <eOperations name="calculateTotalValue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.itemGroups->collect(g | g.quantity * g.price)->sum()"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemGroups" upperBound="-1"
        eType="ecore:EClass /VendingMachineUAQ/model/vendingMachineUAQ.ecore#//ItemGroup"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastRestocked" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availableSlots" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.capacity - self.itemGroups->collect(g | g.quantity)->sum()"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
