<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vendingMachineUAQ" nsURI="http://www.example.org/vendingMachineUAQ"
    nsPrefix="vendingMachineUAQ">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VendingMachine" eSuperTypes="#//NamedElement #//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//MachineState"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keypad" lowerBound="1"
        eType="#//InputDevice" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paymentModule" lowerBound="1"
        eType="#//PaymentModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dispenser" lowerBound="1"
        eType="#//Dispenser" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inventory" lowerBound="1"
        eType="#//Inventory" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidCoordinates"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidCoordinates" value="self.latitude >= -90 and self.latitude &lt;= 90 and self.longitude >= -180 and self.longitude &lt;= 180"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latitude" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitude" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputDevice" eSuperTypes="#//Operable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="#//STATE_OPERATIONS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dispenser" eSuperTypes="#//Operable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//MachineState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentStage" lowerBound="1"
        eType="#//STATES">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.state.stage"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MachineState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stage" lowerBound="1" eType="#//STATES"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="STATE_OPERATIONS">
    <eLiterals name="SELECT_ITEM_collectCoin"/>
    <eLiterals name="SELECT_ITEM_sendInput" value="1"/>
    <eLiterals name="PROCESSING_ITEM_processItem" value="2"/>
    <eLiterals name="ITEM_DISPATCHED_dispatchChange" value="3"/>
    <eLiterals name="WAIT_FOR_PAYMENT_collectCoin" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PAYMENT_METHODS">
    <eLiterals name="Coin"/>
    <eLiterals name="App" value="1"/>
    <eLiterals name="NFC" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="STATES">
    <eLiterals name="SELECT_ITEM"/>
    <eLiterals name="WAIT_FOR_PAYMENT" value="1"/>
    <eLiterals name="PROCESSING_PAYMENT" value="2"/>
    <eLiterals name="PROCESSING_ITEM" value="3"/>
    <eLiterals name="ITEM_DESPATCHED" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaymentModule" eSuperTypes="#//Operable">
    <eOperations name="isPaymentSuccessful" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.state.stage = STATES::PROCESSING_PAYMENT and not self.paymentType.oclIsUndefined()"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paymentType" lowerBound="1"
        eType="#//PAYMENT_METHODS"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//MachineState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductGroup" eSuperTypes="#//Identifiable #//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PositiveStock"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="PositiveStock" value="self.stock > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stock" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageUrl" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//Product" containment="true" eOpposite="#//Product/group"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Identifiable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expirationDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1" eType="#//ProductGroup"
        eOpposite="#//ProductGroup/products"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inventory" eSuperTypes="#//Identifiable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NonNegativeCapacity"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NonNegativeCapacity" value="self.maxCapacity >= 0"/>
    </eAnnotations>
    <eOperations name="calculateTotalValue" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="self.productGroups->collect(g | g.stock * g.price)->sum()"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productGroups" upperBound="-1"
        eType="#//ProductGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCapacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastRestockedDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availableSlots" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.maxCapacity - self.productGroups->collect(g | g.stock)->sum()"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
